import "./variables.css";
import "./globals.css";

import { AppHeader } from "../components/app-header";
import { Provider } from "react-redux";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

 function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body>
					<AppHeader />
					{children}
			</body>
		</html>
	);
}

export default RootLayout;