import "./variables.css";
import "./globals.css";

import { AppHeader } from "../components/app-header";

export const metadata = {
	title: "Next.js",
	description: "Generated by Next.js",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body>
        <AppHeader/>
				{children}
			</body>
		</html>
	);
}
